// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrxbhvgbyeiozhoomwkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyeGJodmdieWVpb3pob29td2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjMyMDUsImV4cCI6MjA2ODg5OTIwNX0.i11P-c8LqK2wHQiv3Pyg7nNRMMWCVp8TiSq_ASvwWpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});